version: "3.8"

services:
  postgres:
    image: postgres
    container_name: playground-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - data_postgres:/var/lib/postgresql/data

volumes:
  data_postgres:
